development:
  adapter: postgresql
  encoding: unicode
  # database: skybuddyp
  database: alsg
  host: localhost
  pool: 5
  username: skykog
  password: spindoctor

test:
  adapter: postgresql
  encoding: unicode
  # database: skybuddyp
  database: alsgtest
  host: localhost
  pool: 5
  username: skykog
  password: spindoctor

